### PR TITLE
Add test for schema url_mapping via entry points

### PR DESCRIPTION
**Pull request by jdavies-st**
This is to try to debug a problem on Windows.

https://github.com/astropy/astropy/issues/8683

### CODE REVIEW

**Comment by pllim** [comment]
From my error:
```
 Invalid argument: '/C:/.../site-packages/asdf/schemas/stsci.edu/asdf/core/table-1.0.0.yaml'
```

I think it was trying to read in a schema that shipped with `asdf`, not from some HTTP site.

**Comment by pllim** [comment]
Now, I see the failure on Astropy too: https://ci.appveyor.com/project/Astropy/astropy/builds/24435056

xref astropy/astropy#8688

**Comment by jdavies-st** [comment]
Well, at least we now have consistent failures on Windows.

**Comment by jdavies-st** [comment]
Let's see if we can reproduce that failure over in this package.

**Comment by pllim** [comment]
Still passed here! That's bad, right?

**Comment by jdavies-st** [comment]
It means that the problem is in the `astropy` version of the test.  Fixed over there.  Closing this PR.

**Comment by jdavies-st** [comment]
Maybe it would be good to actually add this test in `asdf`, as I believe it utilizes a different path through the code from the others.  It can't hurt.

**Pull request merged**
