### PR TITLE
Documentation improvements based on feedback

### PR DESCRIPTION
**Pull request by drdavella**
@perrygreenfield I haven't yet found anything about making the code blocks larger, but I'll keep digging.

### CODE REVIEW

**Comment by perrygreenfield** [comment]
That's weird. One would think that skinny code blocks would be an issue for many. Is it a sphinx thing?

**Comment by perrygreenfield** [comment]
On further experimentation, they do get wider, but only in proportion to the width of the whole page. And there is a whole lot of empty space on the right in doing so. Is there a way to get rid of that empty margin, or make it a lot smaller?

**Comment by perrygreenfield** [comment]
Unless there is some TeX'y way of giving the box and text all the elasticity for width changes (i.e., assign all increases to this item and not sidebar or margin). Otherwise that will have to do.

**Comment by drdavella** [comment]
I'm going to look into it a little more, but that will be my fallback. I think I can provide custom CSS settings, but I'm not sure how much control that will really give me.

**Comment by drdavella** [comment]
@perrygreenfield I found a cool CSS hack that will allow the code blocks to automatically expand when you hover over them. I like this a bit better than universally making the margins wider because I think it helps preserve the readability of the rest of the text. Let me know what you think.

**Pull request merged**
